#!/usr/bin/env python3
"""Does every path the paper names exist in the repository a reader clones?

WHY THIS EXISTS
---------------
The paper is written in a private tree and read from a public one. The two have
different layouts -- `src_modifications/` against `src/`, `scripts/` against the
repository root, `src_modifications/bench/` against `benchmarks/` -- so a path
that resolves perfectly while writing can be a dead reference to everyone else.

The existing citation check validates against the PRIVATE tree, which is correct
for its purpose and blind to this. A reviewer found `src_modifications/` twice
and `scripts/` three times in `arxiv.md` after cloning the public repository,
and separately found the paper naming three check scripts that were not in it at
all. Their remark is the reason this file exists: *someone who looks for the
gate and cannot find it then doubts everything else.*

WHAT IT CHECKS
--------------
Every repository-relative path named by either rendering of the paper must exist
in the public checkout. Both renderings, because they drift from each other and
the .tex is the one that gets submitted.

Paths that are deliberately not in the public tree are listed in EXTERNAL with
where they do live -- an upstream llama.cpp file, a HuggingFace repository, a
generated artefact. An entry there is a claim that the path is external, not a
way to silence the check.

Exit 0 when every path resolves, 1 when one does not.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUB = ROOT / "../bitnet-t5b"
PAPERS = [ROOT / "paper/arxiv.md", ROOT / "paper/bitnet-baremetal-t5b.tex"]

# Named in the paper, deliberately absent from the public tree, with where each
# actually lives. Adding a line here asserts that; it does not excuse a typo.
EXTERNAL = {
    "src/models/bitnet.cpp":     "upstream llama.cpp, patched by the integration",
    "ggml/src/ggml-cpu/quants.c": "upstream ggml",
    "ggml-common.h":             "upstream ggml",
    "llama-model.cpp":           "upstream llama.cpp",
    "src/ggml_i2s_ternary.c":    "generated by tools/fetch_i2s_reference.sh",
    "src/ggml_i2s_ternary.h":    "generated by tools/fetch_i2s_reference.sh",
    "models/ggml-model-t5b.gguf": "produced by tools/gguf_to_t5b.py, not committed",
}

# Roots of the PUBLIC layout: a token starting with one of these is a repository
# path and must resolve.
ROOTS = ("src/", "benchmarks/", "tools/", "results/", "integration/", "paper/")

# Roots of the PRIVATE layout. These resolve while writing and for nobody else,
# which is exactly the failure this file exists to catch -- so they are detected
# and always reported, never filtered out. The first version of this check
# listed only the public roots, so a private path was dropped before comparison
# and its negative control did not fire.
PRIVATE_ROOTS = ("src_modifications/", "scripts/", "package/", "as-specified/")

# Bare filenames the prose names without a directory. Checked by searching the
# whole public tree, because "run mutation_test.sh" is a claim that the file is
# there just as much as a full path is.
# Hyphens are part of a filename, not a boundary: without them this matched
# "common.h" inside "ggml-common.h" and "integration.patch" inside
# "t5b-integration.patch", then reported both as missing. The lookbehind stops
# a full path being re-reported as its own tail.
BARE = re.compile(r"(?<![\w./-])([a-z0-9][a-z0-9_-]*\.(?:py|sh|c|h|txt|patch))\b")


def paths_in(text: str, is_tex: bool):
    if is_tex:
        text = re.sub(r"\\code\{([^}]*)\}", r" \1 ", text).replace("\\_", "_")
        text = text.replace("\\{", "{").replace("\\}", "}")
    out = set()
    for m in re.finditer(r"[A-Za-z0-9_][A-Za-z0-9_./-]*\.[A-Za-z]{1,5}\b", text):
        t = m.group(0)
        if t.startswith(ROOTS) or t.startswith(PRIVATE_ROOTS):
            out.add(t)
    # Brace forms the prose uses for pairs: src/ternary_t5b.{c,h}
    for m in re.finditer(r"([A-Za-z0-9_./-]+)\.\{([a-z,]+)\}", text):
        if m.group(1).startswith(ROOTS + PRIVATE_ROOTS):
            for ext in m.group(2).split(","):
                out.add(f"{m.group(1)}.{ext}")
    # Bare filenames, which the prose uses freely.
    for m in BARE.finditer(text):
        out.add(m.group(1))
    return out


def main() -> int:
    if not PUB.exists():
        print("  public checkout not present -- skipping.")
        return 0

    bad, checked = [], set()
    for paper in PAPERS:
        if not paper.exists():
            continue
        for t in sorted(paths_in(paper.read_text(), paper.suffix == ".tex")):
            checked.add(t)
            if t.startswith(PRIVATE_ROOTS):
                bad.append((paper.name, f"{t}   [private layout]"))
                continue
            if t in EXTERNAL or (PUB / t).exists():
                continue
            # Also accept a bare filename found anywhere in the tree: the prose
            # sometimes names a file without its directory.
            if list(PUB.rglob(Path(t).name)):
                continue
            bad.append((paper.name, t))

    print("PAPER PATHS: every path the paper names, against the public tree")
    print(f"  distinct paths checked   {len(checked)}")
    print(f"  declared external        {len(EXTERNAL)}")

    if not bad:
        print("\nPASS -- every path resolves in the repository a reader clones.")
        return 0

    print(f"\n  Named by the paper, absent from the public tree ({len(bad)}):")
    for src, t in bad:
        print(f"    {src}: {t}")
    print("\nFAIL -- a reader following these finds nothing. Either ship the")
    print("  file, correct the path to the public layout, or add it to EXTERNAL")
    print("  with where it lives.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
