#!/usr/bin/env python3
"""Does every path the paper names exist in the repository a reader clones?

WHY THIS EXISTS
---------------
The paper is written in a private tree and read from a public one. The two have
different layouts -- `src_modifications/` against `src/`, `scripts/` against the
repository root, `src_modifications/bench/` against `benchmarks/` -- so a path
that resolves perfectly while writing can be a dead reference to everyone else.

The existing citation check validates against the PRIVATE tree, which is correct
for its purpose and blind to this. A reviewer found `src_modifications/` twice
and `scripts/` three times in `arxiv.md` after cloning the public repository,
and separately found the paper naming three check scripts that were not in it at
all. Their remark is the reason this file exists: *someone who looks for the
gate and cannot find it then doubts everything else.*

WHAT IT CHECKS
--------------
Every repository-relative path named by any rendering of the paper must exist in
the public checkout: the Markdown, the long .tex, and the short .tex, because
they drift from each other and it is the .tex files that get submitted. Comments
are stripped from the .tex first -- a path named only in a `%` line is not in the
document a reader sees, and demanding it would be a failure for a reason the
error message misstates.

It also checks the evidence files that SHIP. results/*.txt was outside every
gate, which is how an evidence file came to name another evidence file that the
public tree does not carry. Those are transcripts, so they are held to a weaker
rule than the paper: the question is whether a reader can find the named
artefact at all, not whether the transcript spells the public layout.

Paths that are deliberately not in the public tree are listed in EXTERNAL with
where they do live -- an upstream llama.cpp file, a HuggingFace repository, a
generated artefact. An entry there is a claim that the path is external, not a
way to silence the check.

Exit 0 when every path resolves, 1 when one does not.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The tree a reader clones: the sibling when run from the private repository,
# THIS one when run from the public repository itself. Assuming the sibling made
# this silently skip inside a fresh clone -- the exact situation it exists to
# check -- which is the same layout mistake it was written to catch.
PUB = ROOT / "../bitnet-t5b"
if not PUB.exists() or (ROOT / "Makefile").exists() and (ROOT / "benchmarks").exists():
    PUB = ROOT
PAPERS = [
    ROOT / "paper/arxiv.md",
    ROOT / "paper/bitnet-baremetal-t5b.tex",
    # The submission, which was outside this gate until a cold-clone audit
    # pointed out that the document a stranger is most likely to read first was
    # the one document whose paths nothing checked.
    ROOT / "paper/short/t5b-short.tex",
]

# Named in the paper, deliberately absent from the public tree, with where each
# actually lives. Adding a line here asserts that; it does not excuse a typo.
EXTERNAL = {
    "src/models/bitnet.cpp":     "upstream llama.cpp, patched by the integration",
    "src/llama-graph.h":    "upstream llama.cpp, inside the image",
    "ggml/src/ggml-cpu/quants.c": "upstream ggml",
    "arch/x86/quants.c":         "upstream ggml, arch-specific TQ1_0 kernel",
    "arch/arm/quants.c":         "upstream ggml, arch-specific TQ1_0 kernel",
    "ggml-common.h":             "upstream ggml",
    "llama-model.cpp":           "upstream llama.cpp",
    "src/ggml_i2s_ternary.c":    "generated by tools/fetch_i2s_reference.sh",
    "src/ggml_i2s_ternary.h":    "generated by tools/fetch_i2s_reference.sh",
    "models/ggml-model-t5b.gguf": "produced by tools/gguf_to_t5b.py, not committed",
    "ref-common/pack3.c":        "NTRU reference implementation, github.com/jschanck/ntru",
}

# Roots of the PUBLIC layout: a token starting with one of these is a repository
# path and must resolve.
ROOTS = ("src/", "benchmarks/", "tools/", "results/", "integration/", "paper/")

# Named by the paper at the repository root rather than under a directory.
ROOT_FILES = ("CHANGELOG.md", "Makefile", "NOTICE", "LICENSE")

# Roots of the PRIVATE layout. These resolve while writing and for nobody else,
# which is exactly the failure this file exists to catch -- so they are detected
# and always reported, never filtered out. The first version of this check
# listed only the public roots, so a private path was dropped before comparison
# and its negative control did not fire.
PRIVATE_ROOTS = ("src_modifications/", "scripts/", "package/", "as-specified/")

# Bare filenames the prose names without a directory. Checked by searching the
# whole public tree, because "run mutation_test.sh" is a claim that the file is
# there just as much as a full path is.
# Hyphens are part of a filename, not a boundary: without them this matched
# "common.h" inside "ggml-common.h" and "integration.patch" inside
# "t5b-integration.patch", then reported both as missing. The lookbehind stops
# a full path being re-reported as its own tail.
BARE = re.compile(r"(?<![\w./-])([a-z0-9][a-z0-9_-]*\.(?:py|sh|c|h|txt|patch))\b")

# Build artefacts. Generated by a build, never shipped, and not a reference a
# reader is meant to follow -- so a transcript naming one is not a dead link.
ARTEFACTS = (".o", ".so", ".a")


def strip_tex_comments(text: str) -> str:
    r"""Drop LaTeX comments, which no reader of the rendered paper can see.

    A `%` starts a comment unless it is escaped as `\%`. A backslash escapes
    whatever follows, so stepping over pairs also handles `\\` correctly.

    This is required and not cosmetic. The short paper names
    tools/check_short_parity.py exactly once, on line 12, inside its `%` header
    block. Without stripping, this gate would demand that the public tree carry
    a path because a SOURCE COMMENT mentions it, and would fail on something
    that is not in the document at all -- a gate failing for a reason its own
    error message misstates, which is worse than not gating.
    """
    out = []
    for line in text.split("\n"):
        i = 0
        while i < len(line):
            if line[i] == "\\":
                i += 2          # an escaped char: step over the pair
                continue
            if line[i] == "%":
                line = line[:i]
                break
            i += 1
        out.append(line)
    return "\n".join(out)


def results_refs(pub: Path):
    """Dead references inside the evidence files that actually ship.

    results/*.txt sat outside every gate, which is how evidence came to ship
    naming files the public tree does not have. The scope is the results files
    PRESENT IN THE PUBLIC TREE, not a list kept here: shipping is what makes a
    reference reader-facing, and a second copy of sync_public.sh's list would be
    a second thing to drift.

    The rule is deliberately weaker than the paper's, because these are
    TRANSCRIPTS. `make -C src_modifications ...` is a true record of what was
    run, and rewriting it to match the public layout would falsify evidence. So
    a path resolves if its basename exists anywhere in the public tree, and only
    a name that is nowhere in it -- which no reader can follow by any route --
    is reported.
    """
    bad = []
    for p in sorted((pub / "results").glob("*.txt")):
        src = ROOT / "results" / p.name
        if not src.exists():
            bad.append((f"results/{p.name}", "ships, but has no original in this tree"))
            continue
        seen = set()
        for m in re.finditer(r"[A-Za-z0-9_][A-Za-z0-9_./-]*\.[A-Za-z]{1,5}\b",
                             src.read_text(errors="replace")):
            t = m.group(0)
            if t.startswith(ROOTS + PRIVATE_ROOTS) and not t.endswith(ARTEFACTS):
                seen.add(t)
        for t in sorted(seen):
            if t in EXTERNAL or (pub / t).exists():
                continue
            if list(pub.rglob(Path(t).name)):
                continue
            bad.append((f"results/{p.name}", t))
    return bad


def paths_in(text: str, is_tex: bool):
    if is_tex:
        text = strip_tex_comments(text)
        text = re.sub(r"\\code\{([^}]*)\}", r" \1 ", text).replace("\\_", "_")
        text = text.replace("\\{", "{").replace("\\}", "}")
    out = set()
    for m in re.finditer(r"[A-Za-z0-9_][A-Za-z0-9_./-]*\.[A-Za-z]{1,5}\b", text):
        t = m.group(0)
        if t.startswith(ROOTS) or t.startswith(PRIVATE_ROOTS):
            out.add(t)
    # Brace forms the prose uses for pairs: src/ternary_t5b.{c,h}
    for m in re.finditer(r"([A-Za-z0-9_./-]+)\.\{([a-z,]+)\}", text):
        if m.group(1).startswith(ROOTS + PRIVATE_ROOTS):
            for ext in m.group(2).split(","):
                out.add(f"{m.group(1)}.{ext}")
    # Bare filenames, which the prose uses freely.
    for m in BARE.finditer(text):
        out.add(m.group(1))
    return out


def main() -> int:
    if not PUB.exists():
        print("  public checkout not present -- skipping.")
        return 0

    bad, checked = [], set()
    for paper in PAPERS:
        if not paper.exists():
            continue
        for t in sorted(paths_in(paper.read_text(), paper.suffix == ".tex")):
            checked.add(t)
            if t.startswith(PRIVATE_ROOTS):
                bad.append((paper.name, f"{t}   [private layout]"))
                continue
            if t in EXTERNAL or (PUB / t).exists():
                continue
            # Also accept a bare filename found anywhere in the tree: the prose
            # sometimes names a file without its directory.
            if list(PUB.rglob(Path(t).name)):
                continue
            bad.append((paper.name, t))

    dead = results_refs(PUB)
    shipped = len(list((PUB / "results").glob("*.txt")))

    print("PAPER PATHS: every path the paper names, against the public tree")
    print(f"  distinct paths checked   {len(checked)}")
    print(f"  declared external        {len(EXTERNAL)}")
    print(f"  shipped evidence files   {shipped}")

    if not bad and not dead:
        print("\nPASS -- every path resolves in the repository a reader clones,")
        print("  and no shipped evidence file points at something that is not there.")
        return 0

    if bad:
        print(f"\n  Named by the paper, absent from the public tree ({len(bad)}):")
        for src, t in bad:
            print(f"    {src}: {t}")
        print("\nFAIL -- a reader following these finds nothing. Either ship the")
        print("  file, correct the path to the public layout, or add it to EXTERNAL")
        print("  with where it lives.")

    if dead:
        print(f"\n  Shipped evidence naming something the public tree lacks ({len(dead)}):")
        for src, t in dead:
            print(f"    {src}: {t}")
        print("\nFAIL -- these evidence files ship, so a reader reads them and")
        print("  follows what they name. Ship the named file too (add it to")
        print("  sync_public.sh's EXTRA list); do NOT rewrite the transcript to")
        print("  match, because what it records is what was actually run.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
