#!/usr/bin/env python3
"""Does every shipped source have a rule that builds it?

WHY THIS EXISTS
---------------
`benchmarks/bench_probe_cost.c` was copied into the public repository and never
given a Makefile rule. It shipped, it was cited by the paper, and `make` did not
build it -- a file that looks present and is dead. Nothing caught it: the suites
pass without it, `make` exits 0 without it, and the sync check only compares it
against its original, which was equally unbuilt.

That is a distinct failure from the stale-copy class the other checks cover. A
copy can be perfectly current and still be unreachable.

So: every .c under benchmarks/ and src/ must be named by the Makefile, either as
a target's prerequisite or in a variable it expands. Headers are exempt --- they
are reached by inclusion, not by a rule --- and so is anything the Makefile
names as deliberately generated.

Run against the public checkout, which is the one with a Makefile that claims to
build everything. Exit 0 when every source is reachable, 1 when one is not.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# This file runs UNCHANGED in both trees, which is deliberate: it is copied
# between them by scripts/sync_public.sh, and a copy that needed editing on
# arrival is a copy that drifts. The two layouts differ --
#
#   private:  scripts/apply_integration.py   ../bitnet-t5b/integration/*.patch
#   public:   integration/apply_integration.py   integration/*.patch
#
# -- so paths are LOCATED rather than assumed, and a miss says which candidates
# were tried instead of failing on a stack trace.
def locate(*candidates):
    """First existing path among the candidates, or None."""
    for c in candidates:
        p = (ROOT / c).resolve()
        if p.exists():
            return p
    return None

# The tree whose Makefile claims to build everything: this one when run from the
# public checkout, the sibling when run from the private one.
_mk = locate("Makefile", "../bitnet-t5b/Makefile")
PUB = _mk.parent if _mk else None

# Generated by tools/fetch_i2s_reference.sh rather than checked in; the Makefile
# names it through the I2S_REF variable and guards on its presence.
EXEMPT = {"ggml_i2s_ternary.c"}


def main() -> int:
    if PUB is None:
        print("  no Makefile found in either layout -- skipping.")
        return 0
    mk = PUB / "Makefile"

    # NON-COMMENT lines only. The first version of this check matched the whole
    # file, so a source named in a comment counted as built -- and its negative
    # control duly failed to fire when the rule was deleted but the comment
    # above it survived. A check that a prose mention satisfies is not checking
    # the build.
    text = "\n".join(l for l in mk.read_text().splitlines()
                     if not l.lstrip().startswith("#"))
    missing = []
    checked = 0

    for d in ("benchmarks", "src"):
        for p in sorted((PUB / d).glob("*.c")):
            if p.name in EXEMPT:
                continue
            checked += 1
            # Named directly, or reachable through a variable holding its stem.
            if p.name in text or p.stem in text:
                continue
            missing.append(f"{d}/{p.name}")

    print("BUILDABLE: every shipped source against the Makefile")
    print(f"  sources checked   {checked}")

    if not missing:
        print("\nPASS -- every .c is named by a build rule.")
        return 0

    print(f"\n  Shipped but not built ({len(missing)}):")
    for m in missing:
        print(f"    {m}")
    print("\nFAIL -- these files are in the repository and `make` ignores them.")
    print("  Either add a rule or remove the file; a source nobody builds is")
    print("  a source nobody compiles, and it rots without saying so.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
