#!/usr/bin/env python3
"""Do the two renderings of the paper still say the same thing?

WHY THIS EXISTS
---------------
The paper is maintained as `paper/arxiv.md` and `paper/bitnet-baremetal-t5b.tex`.
The `.tex` is what gets submitted; the `.md` is what people read in the
repository. They are edited by hand, and they have drifted THREE times:

  1. The `.tex` fell an entire revision behind and a reviewer caught it.
  2. Fixed by copying, which fixed that revision and nothing structural.
  3. Caught again by the same reviewer, worse: `.tex` was missing the whole
     TQ1_0 comparison (the paper's most important new content), still carried
     the retracted claim that removing dead neurons "needs no format change and
     no kernel work" and is "unconditionally exact", and quoted 30% for a
     quantity measured at 43.6% two subsections earlier.

The right fix is one source. `pandoc` is not available here and installing it
was declined, so the fix available is this: make the drift MECHANICALLY VISIBLE
before it reaches a reviewer.

WHAT IT COMPARES, AND WHY NUMBERS
---------------------------------
Prose cannot be diffed across two markup languages without a converter. Numbers
can. Every drift above showed up as a number present in one file and absent from
the other -- 1.60755 and 1085565120 and 43.95 when §7.6 was missing, 0.751 and
2.35 when §8 was stale, 43.6 against 30 in the contradiction. So this extracts
every numeric literal from both files, normalises the two spellings to the same
token, and reports what appears in one and not the other.

It is a smoke detector and not a proof: prose can diverge with identical
numbers, and it says so rather than implying otherwise. What it catches is the
failure that actually happened, three times.

Numbers are normalised so the two markups compare equal:
    \\num{1187801280}, 1,187,801,280 and 1187801280   -> 1187801280
    \\SI{4.76}{\\percent}, 4.76%                       -> 4.76
    \\numrange{3.0}{4.0}                              -> 3.0 and 4.0

Exit 0 when they agree, 1 when they do not.
"""
import re
import sys
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
MD = ROOT / "paper/arxiv.md"
TEX = ROOT / "paper/bitnet-baremetal-t5b.tex"

# Numbers that legitimately appear in one file only, each with the reason. An
# entry here is a claim that this difference is intended; adding one without a
# reason defeats the check.
ALLOWED = {
    # LaTeX plumbing: font sizes, column widths, version numbers in the preamble.
    "0.36", "0.56", "0.44", "0.52", "0.62", "1.0", "0.5", "11", "12", "10",
    # Markdown-only: the fenced table alignment rows and heading numerals carry
    # no claim, and section numbers are generated by LaTeX rather than written.
    "7.6", "7.4", "7.3", "7.1", "7.2", "7.5", "9.1", "9.2", "5.2", "5.3", "4.1",
    "4.2", "4.3", "4.4", "3.1", "3.2", "3.3", "2.1", "2.2", "1.1",
}

NUM = re.compile(r"\d+(?:[.,]\d+)*")

# Four classes of digit that are pointers or plumbing rather than claims, and
# that legitimately appear in one rendering only. Stripping them beats listing
# their values in ALLOWED, which would have to grow every time a date or an
# equation is added.
STRUCTURAL = [
    (re.compile(r"\d{4}-\d{2}-\d{2}"), " "),        # ISO dates in the front matter
    (re.compile(r"\\tag\{\d+\}"), " "),             # manual equation tags; LaTeX numbers its own
    (re.compile(r"\.(?:txt|md|c|h|py|sh|cpp|json):\d+"), " "),  # file:line pointers
    (re.compile(r"^#{1,6}\s+[\d.]+[a-z]?\s", re.M), " "),       # markdown heading numerals
]


def numbers(text: str, is_tex: bool) -> Counter:
    # Equation cross-references. Markdown has to write the number -- "by (18)"
    # -- where LaTeX writes \eqref and lets the compiler assign it, so these are
    # in one rendering only by construction.
    #
    # A blanket strip of "(N)" would be wrong and this was checked rather than
    # assumed: the markdown also contains "the type identifier used (43)", a
    # real claim about a GGML type number. So only those N that ACTUALLY LABEL
    # an equation in this file are removed -- a reference must refer to
    # something. 43 tags no equation and survives; 18 does and does not.
    tagged = set(re.findall(r"\\tag\{(\d+)\}", text))
    if tagged:
        text = re.sub(r"\((\d+)\)",
                      lambda m: " " if m.group(1) in tagged else m.group(0), text)
        text = re.sub(r"\\tag\{\d+\}", " ", text)

    for pat, rep in STRUCTURAL:
        text = pat.sub(rep, text)
    if is_tex:
        # Unwrap the siunitx forms first so their payloads survive as plain
        # numbers; \numrange and \SIrange carry two.
        text = re.sub(r"\\num(?:range)?\{([^}]*)\}\{([^}]*)\}", r" \1 \2 ", text)
        text = re.sub(r"\\SIrange\{([^}]*)\}\{([^}]*)\}\{[^}]*\}", r" \1 \2 ", text)
        text = re.sub(r"\\(?:num|SI)\{([^}]*)\}(?:\{[^}]*\})?", r" \1 ", text)
        # Strip the preamble: package options and geometry are not claims.
        body = text.split(r"\begin{document}", 1)
        text = body[1] if len(body) > 1 else text
        # Bibliography plumbing: the {99} width argument and every citation key.
        # \bibitem{bitnet158} is a label, not the number 158, and reading it as
        # one made this check report a difference that did not exist.
        text = re.sub(r"\\begin\{thebibliography\}\{[^}]*\}", " ", text)
        text = re.sub(r"\\(?:bibitem|cite|label|ref|eqref)\{[^}]*\}", " ", text)
        # LaTeX control sequences can contain digits that are not numbers.
        text = re.sub(r"\\[a-zA-Z]+", " ", text)
    else:
        # The markdown carries a few \SI{} forms verbatim; treat them the same.
        text = re.sub(r"\\(?:num|SI)\{([^}]*)\}(?:\{[^}]*\})?", r" \1 ", text)
        # Fenced code blocks are commands, not claims.
        text = re.sub(r"```.*?```", " ", text, flags=re.S)
        # Markdown table separators (|---:|) and heading hashes.
        text = re.sub(r"^\s*\|[\s:|-]+\|\s*$", " ", text, flags=re.M)

    # LaTeX digit separators, which appear in the markdown too because its maths
    # is LaTeX: 32{,}512 and 32\,512 are both the number 32512. Removing these
    # before matching stops the extractor from inventing tokens like "024" out
    # of one number written with separators.
    text = text.replace("{,}", "").replace("\\,", "").replace("{\\,}", "")

    out = Counter()
    for m in NUM.finditer(text):
        tok = m.group(0).replace(",", "")
        # Drop a trailing decimal zero difference: 2.0 and 2.00 are the same
        # claim written twice, and chasing that is noise.
        if "." in tok:
            tok = tok.rstrip("0").rstrip(".") or "0"
        if tok in ALLOWED or len(tok) == 0:
            continue
        # Single digits are almost all structural (list markers, small counts in
        # prose) and produce noise without catching drift.
        if len(tok) < 2:
            continue
        out[tok] += 1
    return out


def main() -> int:
    for p in (MD, TEX):
        if not p.exists():
            print(f"missing: {p}", file=sys.stderr)
            return 2

    md = numbers(MD.read_text(), is_tex=False)
    tex = numbers(TEX.read_text(), is_tex=True)

    only_md = sorted(set(md) - set(tex))
    only_tex = sorted(set(tex) - set(md))

    print("PAPER PARITY: arxiv.md against bitnet-baremetal-t5b.tex")
    print(f"  distinct numeric claims   md {len(md):4d}   tex {len(tex):4d}")
    print(f"  shared                    {len(set(md) & set(tex)):4d}")

    if not only_md and not only_tex:
        print("\nPASS -- every numeric claim appears in both renderings.")
        print("  This does NOT prove the prose agrees. It proves the failure")
        print("  that has happened three times has not happened again.")
        return 0

    if only_md:
        print(f"\n  In arxiv.md but NOT in the .tex ({len(only_md)}):")
        for t in only_md:
            print(f"    {t}")
    if only_tex:
        print(f"\n  In the .tex but NOT in arxiv.md ({len(only_tex)}):")
        for t in only_tex:
            print(f"    {t}")

    print("\nFAIL -- the two renderings carry different numbers.")
    print("  The .tex is what gets submitted. If a claim is only in the .md,")
    print("  it is not in the paper. Port it, or add the token to ALLOWED with")
    print("  the reason it legitimately differs.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
